services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=chem-lab-db
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  express:
    build:
      context: ./
    container_name: express
    ports:
      - "5226:5226"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/chem-lab-db

volumes:
  mongo-data:
